set_project("finepaper")
set_version("0.1.0")
set_languages("c++23")

add_rules("mode.debug", "mode.release")
includes("deps/packages.lua")
add_requires("nodeeditor 3.0.16")

target("finepaper-application")
    add_rules("qt.static")
    set_kind("static")
    add_headerfiles("src/noc/*.h")
    add_headerfiles("src/package/*.h")
    add_headerfiles("src/storage/*.h")
    add_headerfiles("src/execution/*.h")
    add_headerfiles("src/application/*.h")
    add_files("src/noc/*.cpp")
    add_files("src/package/*.cpp")
    add_files("src/storage/*.cpp")
    add_files("src/execution/*.cpp")
    add_files("src/application/*.cpp")
    add_includedirs("src", {public = true})

target("finepaper")
    add_rules("qt.console")
    set_kind("binary")
    set_rundir(os.projectdir())
    add_deps("finepaper-application")
    add_files("src/cli/main.cpp")
    add_includedirs("src")

target("finepaper-gui")
    add_rules("qt.widgetapp")
    add_frameworks("QtConcurrent")
    set_kind("binary")
    set_rundir(os.projectdir())
    add_deps("finepaper-application")
    add_packages("nodeeditor")
    add_files("src/gui/*.cpp")
    add_includedirs("src")

target("finepaper-tests")
    add_rules("qt.console")
    set_kind("binary")
    set_group("test")
    set_default(false)
    add_deps("finepaper-application")
    add_files("tests/core_tests.cpp")
    add_includedirs("src")
    add_defines('FINEPAPER_SOURCE_DIR="' .. path.unix(os.projectdir()) .. '"')
    add_tests("default", {
        trim_output = true
    })

target("finepaper-cli-tests")
    add_rules("qt.console")
    set_kind("binary")
    set_group("test")
    set_default(false)
    add_deps("finepaper")
    add_files("tests/cli_tests.cpp")
    add_defines('FINEPAPER_SOURCE_DIR="' .. path.unix(os.projectdir()) .. '"')
    add_tests("default", {
        trim_output = true
    })

target("finepaper-gui-smoke")
    add_rules("qt.widgetapp")
    add_frameworks("QtConcurrent")
    set_kind("binary")
    set_group("test")
    set_default(false)
    add_deps("finepaper-application")
    add_packages("nodeeditor")
    add_files("tests/gui_smoke_test.cpp")
    add_files("src/gui/main_window.cpp")
    add_files("src/gui/animated_graphics_view.cpp")
    add_files("src/gui/noc_editor_style.cpp")
    add_files("src/gui/noc_node_editor.cpp")
    add_files("src/gui/workbench_view_registry.cpp")
    add_includedirs("src")
    add_defines('FINEPAPER_SOURCE_DIR="' .. path.unix(os.projectdir()) .. '"')
    add_tests("default", {
        trim_output = true,
        runenvs = {QT_QPA_PLATFORM = "offscreen"}
    })
