// Auto-generated by finepaper | NoC: my_noc v1.0
// Network Interface for XP xp_1_1

module ni_xp_xp_1_1 #(
  parameter FLIT_WIDTH = 128,
  parameter NUM_ENDPOINTS = 1
) (
  input  logic clk,
  input  logic rst_n,
  // Endpoint-side interfaces (protocol side)

  input  logic [FLIT_WIDTH-1:0] ep_mem1_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_mem1_flit_out,
  // Router-side interfaces (flit side)

  output logic [FLIT_WIDTH-1:0] ep_mem1_router_flit_in,
  input  logic [FLIT_WIDTH-1:0] ep_mem1_router_flit_out
);
  // Placeholder passthrough logic

  assign ep_mem1_router_flit_in = ep_mem1_flit_in;
  assign ep_mem1_flit_out = ep_mem1_router_flit_out;

endmodule
