
//----------------------------------------------------------------------------
// Auto-generated by finepaper | NoC: my_noc v1.0
//----------------------------------------------------------------------------
//#========================================================================
//#
//#  my_noc: CMN-style generated NoC integration wrapper
//#
//#========================================================================
//#
//# Topology Summary
//# ================
//  - mesh_size      : 2 x 2
//  - xp_count       : 4
//  - link_count     : 4
//  - endpoint_count : 4
//  - master_count   : 2
//  - slave_count    : 2
//  - variant_mode   : per-xp router modules
//  - ni_mode        : per-xp ni modules
//#
//# Global Configuration Parameters
//# ===============================

//  - ADDR_WIDTH           = 32

//  - DATA_WIDTH           = 64

//  - FLIT_WIDTH           = 128

//#
//# XP Inventory
//# ============

//  - NID000 xp_0_0           xy=(0,0) endpoints=ep_cpu0 route=xy vc=2 depth=8

//  - NID001 xp_1_0           xy=(1,0) endpoints=ep_cpu1 route=xy vc=2 depth=8

//  - NID002 xp_0_1           xy=(0,1) endpoints=ep_mem0 route=xy vc=2 depth=8

//  - NID003 xp_1_1           xy=(1,1) endpoints=ep_mem1 route=xy vc=2 depth=8

//#
//# Endpoint / Device Inventory
//# ===========================

//  - ep_cpu0          role=master protocol=axi4     data_width=64 buffer_depth=16 qos=disabled

//  - ep_cpu1          role=master protocol=axi4     data_width=64 buffer_depth=16 qos=disabled

//  - ep_mem0          role=slave  protocol=axi4     data_width=128 buffer_depth=16 qos=disabled

//  - ep_mem1          role=slave  protocol=axi4     data_width=128 buffer_depth=16 qos=disabled

//#
//# Mesh Link Inventory
//# ===================

//  - L000 xp_0_0 -> xp_1_0 dir=east channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L001 xp_0_0 -> xp_0_1 dir=south channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L002 xp_1_0 -> xp_1_1 dir=south channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L003 xp_0_1 -> xp_1_1 dir=east channels=REQ,RSP,DAT,SNP,PUB credits=local

//----------------------------------------------------------------------------

module my_noc_top #(
  parameter DATA_WIDTH = 64,
  parameter FLIT_WIDTH = 128,
  parameter ADDR_WIDTH = 32
) (
  input  logic clk,
  input  logic rst_n,
  input  logic [FLIT_WIDTH-1:0] ep_cpu0_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_cpu0_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_cpu1_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_cpu1_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_mem0_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_mem0_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_mem1_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_mem1_flit_out
);

  //# Internal Signals - Mesh Link Bundle Declarations
  //# ================================================
  // Each directed link keeps the current simplified flit net plus CMN-style
  // placeholder sidebands for valid, credit, snoop, and public channels.

  logic [FLIT_WIDTH-1:0] link_xp_0_0_to_xp_1_0_flit;
  logic                  link_xp_0_0_to_xp_1_0_reqflitv;
  logic                  link_xp_0_0_to_xp_1_0_rspflitv;
  logic                  link_xp_0_0_to_xp_1_0_datflitv;
  logic                  link_xp_0_0_to_xp_1_0_snpflitv;
  logic                  link_xp_0_0_to_xp_1_0_pubflitv;
  logic                  link_xp_0_0_to_xp_1_0_lcrdv;
  logic [7:0]            link_xp_0_0_to_xp_1_0_rinfo;
  logic [15:0]           link_xp_0_0_to_xp_1_0_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_0_to_xp_0_0_flit;
  logic                  link_xp_1_0_to_xp_0_0_reqflitv;
  logic                  link_xp_1_0_to_xp_0_0_rspflitv;
  logic                  link_xp_1_0_to_xp_0_0_datflitv;
  logic                  link_xp_1_0_to_xp_0_0_snpflitv;
  logic                  link_xp_1_0_to_xp_0_0_pubflitv;
  logic                  link_xp_1_0_to_xp_0_0_lcrdv;
  logic [7:0]            link_xp_1_0_to_xp_0_0_rinfo;
  logic [15:0]           link_xp_1_0_to_xp_0_0_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_0_0_to_xp_0_1_flit;
  logic                  link_xp_0_0_to_xp_0_1_reqflitv;
  logic                  link_xp_0_0_to_xp_0_1_rspflitv;
  logic                  link_xp_0_0_to_xp_0_1_datflitv;
  logic                  link_xp_0_0_to_xp_0_1_snpflitv;
  logic                  link_xp_0_0_to_xp_0_1_pubflitv;
  logic                  link_xp_0_0_to_xp_0_1_lcrdv;
  logic [7:0]            link_xp_0_0_to_xp_0_1_rinfo;
  logic [15:0]           link_xp_0_0_to_xp_0_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_0_1_to_xp_0_0_flit;
  logic                  link_xp_0_1_to_xp_0_0_reqflitv;
  logic                  link_xp_0_1_to_xp_0_0_rspflitv;
  logic                  link_xp_0_1_to_xp_0_0_datflitv;
  logic                  link_xp_0_1_to_xp_0_0_snpflitv;
  logic                  link_xp_0_1_to_xp_0_0_pubflitv;
  logic                  link_xp_0_1_to_xp_0_0_lcrdv;
  logic [7:0]            link_xp_0_1_to_xp_0_0_rinfo;
  logic [15:0]           link_xp_0_1_to_xp_0_0_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_0_to_xp_1_1_flit;
  logic                  link_xp_1_0_to_xp_1_1_reqflitv;
  logic                  link_xp_1_0_to_xp_1_1_rspflitv;
  logic                  link_xp_1_0_to_xp_1_1_datflitv;
  logic                  link_xp_1_0_to_xp_1_1_snpflitv;
  logic                  link_xp_1_0_to_xp_1_1_pubflitv;
  logic                  link_xp_1_0_to_xp_1_1_lcrdv;
  logic [7:0]            link_xp_1_0_to_xp_1_1_rinfo;
  logic [15:0]           link_xp_1_0_to_xp_1_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_1_to_xp_1_0_flit;
  logic                  link_xp_1_1_to_xp_1_0_reqflitv;
  logic                  link_xp_1_1_to_xp_1_0_rspflitv;
  logic                  link_xp_1_1_to_xp_1_0_datflitv;
  logic                  link_xp_1_1_to_xp_1_0_snpflitv;
  logic                  link_xp_1_1_to_xp_1_0_pubflitv;
  logic                  link_xp_1_1_to_xp_1_0_lcrdv;
  logic [7:0]            link_xp_1_1_to_xp_1_0_rinfo;
  logic [15:0]           link_xp_1_1_to_xp_1_0_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_0_1_to_xp_1_1_flit;
  logic                  link_xp_0_1_to_xp_1_1_reqflitv;
  logic                  link_xp_0_1_to_xp_1_1_rspflitv;
  logic                  link_xp_0_1_to_xp_1_1_datflitv;
  logic                  link_xp_0_1_to_xp_1_1_snpflitv;
  logic                  link_xp_0_1_to_xp_1_1_pubflitv;
  logic                  link_xp_0_1_to_xp_1_1_lcrdv;
  logic [7:0]            link_xp_0_1_to_xp_1_1_rinfo;
  logic [15:0]           link_xp_0_1_to_xp_1_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_1_to_xp_0_1_flit;
  logic                  link_xp_1_1_to_xp_0_1_reqflitv;
  logic                  link_xp_1_1_to_xp_0_1_rspflitv;
  logic                  link_xp_1_1_to_xp_0_1_datflitv;
  logic                  link_xp_1_1_to_xp_0_1_snpflitv;
  logic                  link_xp_1_1_to_xp_0_1_pubflitv;
  logic                  link_xp_1_1_to_xp_0_1_lcrdv;
  logic [7:0]            link_xp_1_1_to_xp_0_1_rinfo;
  logic [15:0]           link_xp_1_1_to_xp_0_1_globalsig;


  //# Device Attachment Bundle Declarations
  //# =====================================
  // NI-to-router bundles model protocol adapters, request queues, and return
  // paths in the same location a production wrapper would stitch CHI/AXI ports.

  logic [FLIT_WIDTH-1:0] ni_ep_cpu0_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_cpu0_flit;

  logic                  ni_ep_cpu0_tx_credit_valid;
  logic                  ni_ep_cpu0_rx_credit_valid;

  logic [3:0]            ni_ep_cpu0_qos_class;


  logic [FLIT_WIDTH-1:0] ni_ep_cpu1_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_cpu1_flit;

  logic                  ni_ep_cpu1_tx_credit_valid;
  logic                  ni_ep_cpu1_rx_credit_valid;

  logic [3:0]            ni_ep_cpu1_qos_class;


  logic [FLIT_WIDTH-1:0] ni_ep_mem0_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_mem0_flit;

  logic                  ni_ep_mem0_tx_credit_valid;
  logic                  ni_ep_mem0_rx_credit_valid;

  logic [3:0]            ni_ep_mem0_qos_class;


  logic [FLIT_WIDTH-1:0] ni_ep_mem1_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_mem1_flit;

  logic                  ni_ep_mem1_tx_credit_valid;
  logic                  ni_ep_mem1_rx_credit_valid;

  logic [3:0]            ni_ep_mem1_qos_class;



  //# Router Instance Stitching
  //# =========================

  xp_router_xp_0_0 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_0_0 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_out_xp_1_0(link_xp_0_0_to_xp_1_0_flit),
    .flit_in_xp_1_0(link_xp_1_0_to_xp_0_0_flit),
    .flit_out_xp_0_1(link_xp_0_0_to_xp_0_1_flit),
    .flit_in_xp_0_1(link_xp_0_1_to_xp_0_0_flit),
    .ep_cpu0_flit_in(ni_ep_cpu0_to_router_flit),
    .ep_cpu0_flit_out(router_to_ni_ep_cpu0_flit)
  );


  xp_router_xp_1_0 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_1_0 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_0_0(link_xp_0_0_to_xp_1_0_flit),
    .flit_out_xp_0_0(link_xp_1_0_to_xp_0_0_flit),
    .flit_out_xp_1_1(link_xp_1_0_to_xp_1_1_flit),
    .flit_in_xp_1_1(link_xp_1_1_to_xp_1_0_flit),
    .ep_cpu1_flit_in(ni_ep_cpu1_to_router_flit),
    .ep_cpu1_flit_out(router_to_ni_ep_cpu1_flit)
  );


  xp_router_xp_0_1 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_0_1 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_0_0(link_xp_0_0_to_xp_0_1_flit),
    .flit_out_xp_0_0(link_xp_0_1_to_xp_0_0_flit),
    .flit_out_xp_1_1(link_xp_0_1_to_xp_1_1_flit),
    .flit_in_xp_1_1(link_xp_1_1_to_xp_0_1_flit),
    .ep_mem0_flit_in(ni_ep_mem0_to_router_flit),
    .ep_mem0_flit_out(router_to_ni_ep_mem0_flit)
  );


  xp_router_xp_1_1 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_1_1 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_1_0(link_xp_1_0_to_xp_1_1_flit),
    .flit_out_xp_1_0(link_xp_1_1_to_xp_1_0_flit),
    .flit_in_xp_0_1(link_xp_0_1_to_xp_1_1_flit),
    .flit_out_xp_0_1(link_xp_1_1_to_xp_0_1_flit),
    .ep_mem1_flit_in(ni_ep_mem1_to_router_flit),
    .ep_mem1_flit_out(router_to_ni_ep_mem1_flit)
  );


  //# Network Interface Instance Stitching
  //# ====================================

  ni_xp_xp_0_0 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_0_0 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_cpu0_flit_in(ep_cpu0_flit_in),
    .ep_cpu0_flit_out(ep_cpu0_flit_out),
    .ep_cpu0_router_flit_in(ni_ep_cpu0_to_router_flit),
    .ep_cpu0_router_flit_out(router_to_ni_ep_cpu0_flit)
  );


  ni_xp_xp_1_0 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_1_0 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_cpu1_flit_in(ep_cpu1_flit_in),
    .ep_cpu1_flit_out(ep_cpu1_flit_out),
    .ep_cpu1_router_flit_in(ni_ep_cpu1_to_router_flit),
    .ep_cpu1_router_flit_out(router_to_ni_ep_cpu1_flit)
  );


  ni_xp_xp_0_1 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_0_1 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_mem0_flit_in(ep_mem0_flit_in),
    .ep_mem0_flit_out(ep_mem0_flit_out),
    .ep_mem0_router_flit_in(ni_ep_mem0_to_router_flit),
    .ep_mem0_router_flit_out(router_to_ni_ep_mem0_flit)
  );


  ni_xp_xp_1_1 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_1_1 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_mem1_flit_in(ep_mem1_flit_in),
    .ep_mem1_flit_out(ep_mem1_flit_out),
    .ep_mem1_router_flit_in(ni_ep_mem1_to_router_flit),
    .ep_mem1_router_flit_out(router_to_ni_ep_mem1_flit)
  );


endmodule
