// Auto-generated by finepaper | NoC: mesh_3x3 v1.0
// Top-level module instantiating all routers

module mesh_3x3_top #(
  parameter DATA_WIDTH = 64,
  parameter FLIT_WIDTH = 128,
  parameter ADDR_WIDTH = 32
) (
  input  logic clk,
  input  logic rst_n,
  input  logic [FLIT_WIDTH-1:0] ep_0_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_0_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_1_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_1_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_2_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_2_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_3_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_3_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_4_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_4_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_5_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_5_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_6_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_6_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_7_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_7_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_8_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_8_flit_out
);

  logic [FLIT_WIDTH-1:0] link_xp_0_0_to_xp_1_0_flit;

  logic [FLIT_WIDTH-1:0] link_xp_1_0_to_xp_0_0_flit;

  logic [FLIT_WIDTH-1:0] link_xp_0_0_to_xp_0_1_flit;

  logic [FLIT_WIDTH-1:0] link_xp_0_1_to_xp_0_0_flit;

  logic [FLIT_WIDTH-1:0] link_xp_1_0_to_xp_2_0_flit;

  logic [FLIT_WIDTH-1:0] link_xp_2_0_to_xp_1_0_flit;

  logic [FLIT_WIDTH-1:0] link_xp_1_0_to_xp_1_1_flit;

  logic [FLIT_WIDTH-1:0] link_xp_1_1_to_xp_1_0_flit;

  logic [FLIT_WIDTH-1:0] link_xp_2_0_to_xp_2_1_flit;

  logic [FLIT_WIDTH-1:0] link_xp_2_1_to_xp_2_0_flit;

  logic [FLIT_WIDTH-1:0] link_xp_0_1_to_xp_1_1_flit;

  logic [FLIT_WIDTH-1:0] link_xp_1_1_to_xp_0_1_flit;

  logic [FLIT_WIDTH-1:0] link_xp_0_1_to_xp_0_2_flit;

  logic [FLIT_WIDTH-1:0] link_xp_0_2_to_xp_0_1_flit;

  logic [FLIT_WIDTH-1:0] link_xp_1_1_to_xp_2_1_flit;

  logic [FLIT_WIDTH-1:0] link_xp_2_1_to_xp_1_1_flit;

  logic [FLIT_WIDTH-1:0] link_xp_1_1_to_xp_1_2_flit;

  logic [FLIT_WIDTH-1:0] link_xp_1_2_to_xp_1_1_flit;

  logic [FLIT_WIDTH-1:0] link_xp_2_1_to_xp_2_2_flit;

  logic [FLIT_WIDTH-1:0] link_xp_2_2_to_xp_2_1_flit;

  logic [FLIT_WIDTH-1:0] link_xp_0_2_to_xp_1_2_flit;

  logic [FLIT_WIDTH-1:0] link_xp_1_2_to_xp_0_2_flit;

  logic [FLIT_WIDTH-1:0] link_xp_1_2_to_xp_2_2_flit;

  logic [FLIT_WIDTH-1:0] link_xp_2_2_to_xp_1_2_flit;


  xp_router_xp_0_0 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_0_0 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_out_xp_1_0(link_xp_0_0_to_xp_1_0_flit),
    .flit_in_xp_1_0(link_xp_1_0_to_xp_0_0_flit),
    .flit_out_xp_0_1(link_xp_0_0_to_xp_0_1_flit),
    .flit_in_xp_0_1(link_xp_0_1_to_xp_0_0_flit)
  );

  xp_router_xp_1_0 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_1_0 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_0_0(link_xp_0_0_to_xp_1_0_flit),
    .flit_out_xp_0_0(link_xp_1_0_to_xp_0_0_flit),
    .flit_out_xp_2_0(link_xp_1_0_to_xp_2_0_flit),
    .flit_in_xp_2_0(link_xp_2_0_to_xp_1_0_flit),
    .flit_out_xp_1_1(link_xp_1_0_to_xp_1_1_flit),
    .flit_in_xp_1_1(link_xp_1_1_to_xp_1_0_flit)
  );

  xp_router_xp_2_0 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_2_0 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_1_0(link_xp_1_0_to_xp_2_0_flit),
    .flit_out_xp_1_0(link_xp_2_0_to_xp_1_0_flit),
    .flit_out_xp_2_1(link_xp_2_0_to_xp_2_1_flit),
    .flit_in_xp_2_1(link_xp_2_1_to_xp_2_0_flit)
  );

  xp_router_xp_0_1 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_0_1 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_0_0(link_xp_0_0_to_xp_0_1_flit),
    .flit_out_xp_0_0(link_xp_0_1_to_xp_0_0_flit),
    .flit_out_xp_1_1(link_xp_0_1_to_xp_1_1_flit),
    .flit_in_xp_1_1(link_xp_1_1_to_xp_0_1_flit),
    .flit_out_xp_0_2(link_xp_0_1_to_xp_0_2_flit),
    .flit_in_xp_0_2(link_xp_0_2_to_xp_0_1_flit)
  );

  xp_router_xp_1_1 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_1_1 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_1_0(link_xp_1_0_to_xp_1_1_flit),
    .flit_out_xp_1_0(link_xp_1_1_to_xp_1_0_flit),
    .flit_in_xp_0_1(link_xp_0_1_to_xp_1_1_flit),
    .flit_out_xp_0_1(link_xp_1_1_to_xp_0_1_flit),
    .flit_out_xp_2_1(link_xp_1_1_to_xp_2_1_flit),
    .flit_in_xp_2_1(link_xp_2_1_to_xp_1_1_flit),
    .flit_out_xp_1_2(link_xp_1_1_to_xp_1_2_flit),
    .flit_in_xp_1_2(link_xp_1_2_to_xp_1_1_flit)
  );

  xp_router_xp_2_1 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_2_1 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_2_0(link_xp_2_0_to_xp_2_1_flit),
    .flit_out_xp_2_0(link_xp_2_1_to_xp_2_0_flit),
    .flit_in_xp_1_1(link_xp_1_1_to_xp_2_1_flit),
    .flit_out_xp_1_1(link_xp_2_1_to_xp_1_1_flit),
    .flit_out_xp_2_2(link_xp_2_1_to_xp_2_2_flit),
    .flit_in_xp_2_2(link_xp_2_2_to_xp_2_1_flit)
  );

  xp_router_xp_0_2 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_0_2 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_0_1(link_xp_0_1_to_xp_0_2_flit),
    .flit_out_xp_0_1(link_xp_0_2_to_xp_0_1_flit),
    .flit_out_xp_1_2(link_xp_0_2_to_xp_1_2_flit),
    .flit_in_xp_1_2(link_xp_1_2_to_xp_0_2_flit)
  );

  xp_router_xp_1_2 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_1_2 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_1_1(link_xp_1_1_to_xp_1_2_flit),
    .flit_out_xp_1_1(link_xp_1_2_to_xp_1_1_flit),
    .flit_in_xp_0_2(link_xp_0_2_to_xp_1_2_flit),
    .flit_out_xp_0_2(link_xp_1_2_to_xp_0_2_flit),
    .flit_out_xp_2_2(link_xp_1_2_to_xp_2_2_flit),
    .flit_in_xp_2_2(link_xp_2_2_to_xp_1_2_flit)
  );

  xp_router_xp_2_2 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_2_2 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_2_1(link_xp_2_1_to_xp_2_2_flit),
    .flit_out_xp_2_1(link_xp_2_2_to_xp_2_1_flit),
    .flit_in_xp_1_2(link_xp_1_2_to_xp_2_2_flit),
    .flit_out_xp_1_2(link_xp_2_2_to_xp_1_2_flit)
  );

endmodule
