
//----------------------------------------------------------------------------
// Auto-generated by finepaper | NoC: mesh_3x3 v1.0
//----------------------------------------------------------------------------
//#========================================================================
//#
//#  mesh_3x3: CMN-style generated NoC integration wrapper
//#
//#========================================================================
//#
//# Topology Summary
//# ================
//  - mesh_size      : 3 x 3
//  - xp_count       : 9
//  - link_count     : 12
//  - endpoint_count : 9
//  - master_count   : 5
//  - slave_count    : 4
//  - variant_mode   : per-xp router modules
//#
//# Global Configuration Parameters
//# ===============================

//  - ADDR_WIDTH           = 32

//  - DATA_WIDTH           = 64

//  - FLIT_WIDTH           = 128

//  - MESH                 = {"width" => 3, "height" => 3, "endpoint_map" => {"xp_0_0" => ["ep_0"], "xp_1_0" => ["ep_1"], "xp_2_0" => ["ep_2"], "xp_0_1" => ["ep_3"], "xp_1_1" => ["ep_4"], "xp_2_1" => ["ep_5"], "xp_0_2" => ["ep_6"], "xp_1_2" => ["ep_7"], "xp_2_2" => ["ep_8"]}}

//#
//# XP Inventory
//# ============

//  - NID000 xp_0_0           xy=(0,0) endpoints=ep_0 route=xy vc=2 depth=8

//  - NID001 xp_1_0           xy=(1,0) endpoints=ep_1 route=xy vc=2 depth=8

//  - NID002 xp_2_0           xy=(2,0) endpoints=ep_2 route=xy vc=2 depth=8

//  - NID003 xp_0_1           xy=(0,1) endpoints=ep_3 route=xy vc=2 depth=8

//  - NID004 xp_1_1           xy=(1,1) endpoints=ep_4 route=xy vc=2 depth=8

//  - NID005 xp_2_1           xy=(2,1) endpoints=ep_5 route=xy vc=2 depth=8

//  - NID006 xp_0_2           xy=(0,2) endpoints=ep_6 route=xy vc=2 depth=8

//  - NID007 xp_1_2           xy=(1,2) endpoints=ep_7 route=xy vc=2 depth=8

//  - NID008 xp_2_2           xy=(2,2) endpoints=ep_8 route=xy vc=2 depth=8

//#
//# Endpoint / Device Inventory
//# ===========================

//  - ep_0             role=master protocol=axi4     data_width=64 buffer_depth=16 qos=disabled

//  - ep_1             role=master protocol=axi4     data_width=64 buffer_depth=16 qos=disabled

//  - ep_2             role=master protocol=axi4     data_width=64 buffer_depth=16 qos=disabled

//  - ep_3             role=slave  protocol=axi4     data_width=128 buffer_depth=16 qos=disabled

//  - ep_4             role=slave  protocol=axi4     data_width=128 buffer_depth=16 qos=disabled

//  - ep_5             role=slave  protocol=axi4     data_width=128 buffer_depth=16 qos=disabled

//  - ep_6             role=master protocol=axi4     data_width=64 buffer_depth=16 qos=disabled

//  - ep_7             role=master protocol=axi4     data_width=64 buffer_depth=16 qos=disabled

//  - ep_8             role=slave  protocol=axi4     data_width=128 buffer_depth=16 qos=disabled

//#
//# Mesh Link Inventory
//# ===================

//  - L000 xp_0_0 -> xp_1_0 dir=east channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L001 xp_0_0 -> xp_0_1 dir=south channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L002 xp_1_0 -> xp_2_0 dir=east channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L003 xp_1_0 -> xp_1_1 dir=south channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L004 xp_2_0 -> xp_2_1 dir=south channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L005 xp_0_1 -> xp_1_1 dir=east channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L006 xp_0_1 -> xp_0_2 dir=south channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L007 xp_1_1 -> xp_2_1 dir=east channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L008 xp_1_1 -> xp_1_2 dir=south channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L009 xp_2_1 -> xp_2_2 dir=south channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L010 xp_0_2 -> xp_1_2 dir=east channels=REQ,RSP,DAT,SNP,PUB credits=local

//  - L011 xp_1_2 -> xp_2_2 dir=east channels=REQ,RSP,DAT,SNP,PUB credits=local

//----------------------------------------------------------------------------

module mesh_3x3_top #(
  parameter DATA_WIDTH = 64,
  parameter FLIT_WIDTH = 128,
  parameter ADDR_WIDTH = 32
) (
  input  logic clk,
  input  logic rst_n,
  input  logic [FLIT_WIDTH-1:0] ep_0_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_0_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_1_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_1_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_2_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_2_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_3_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_3_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_4_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_4_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_5_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_5_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_6_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_6_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_7_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_7_flit_out,
  input  logic [FLIT_WIDTH-1:0] ep_8_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_8_flit_out
);

  //# Internal Signals - Mesh Link Bundle Declarations
  //# ================================================
  // Each directed link keeps the current simplified flit net plus CMN-style
  // placeholder sidebands for valid, credit, snoop, and public channels.

  logic [FLIT_WIDTH-1:0] link_xp_0_0_to_xp_1_0_flit;
  logic                  link_xp_0_0_to_xp_1_0_reqflitv;
  logic                  link_xp_0_0_to_xp_1_0_rspflitv;
  logic                  link_xp_0_0_to_xp_1_0_datflitv;
  logic                  link_xp_0_0_to_xp_1_0_snpflitv;
  logic                  link_xp_0_0_to_xp_1_0_pubflitv;
  logic                  link_xp_0_0_to_xp_1_0_lcrdv;
  logic [7:0]            link_xp_0_0_to_xp_1_0_rinfo;
  logic [15:0]           link_xp_0_0_to_xp_1_0_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_0_to_xp_0_0_flit;
  logic                  link_xp_1_0_to_xp_0_0_reqflitv;
  logic                  link_xp_1_0_to_xp_0_0_rspflitv;
  logic                  link_xp_1_0_to_xp_0_0_datflitv;
  logic                  link_xp_1_0_to_xp_0_0_snpflitv;
  logic                  link_xp_1_0_to_xp_0_0_pubflitv;
  logic                  link_xp_1_0_to_xp_0_0_lcrdv;
  logic [7:0]            link_xp_1_0_to_xp_0_0_rinfo;
  logic [15:0]           link_xp_1_0_to_xp_0_0_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_0_0_to_xp_0_1_flit;
  logic                  link_xp_0_0_to_xp_0_1_reqflitv;
  logic                  link_xp_0_0_to_xp_0_1_rspflitv;
  logic                  link_xp_0_0_to_xp_0_1_datflitv;
  logic                  link_xp_0_0_to_xp_0_1_snpflitv;
  logic                  link_xp_0_0_to_xp_0_1_pubflitv;
  logic                  link_xp_0_0_to_xp_0_1_lcrdv;
  logic [7:0]            link_xp_0_0_to_xp_0_1_rinfo;
  logic [15:0]           link_xp_0_0_to_xp_0_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_0_1_to_xp_0_0_flit;
  logic                  link_xp_0_1_to_xp_0_0_reqflitv;
  logic                  link_xp_0_1_to_xp_0_0_rspflitv;
  logic                  link_xp_0_1_to_xp_0_0_datflitv;
  logic                  link_xp_0_1_to_xp_0_0_snpflitv;
  logic                  link_xp_0_1_to_xp_0_0_pubflitv;
  logic                  link_xp_0_1_to_xp_0_0_lcrdv;
  logic [7:0]            link_xp_0_1_to_xp_0_0_rinfo;
  logic [15:0]           link_xp_0_1_to_xp_0_0_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_0_to_xp_2_0_flit;
  logic                  link_xp_1_0_to_xp_2_0_reqflitv;
  logic                  link_xp_1_0_to_xp_2_0_rspflitv;
  logic                  link_xp_1_0_to_xp_2_0_datflitv;
  logic                  link_xp_1_0_to_xp_2_0_snpflitv;
  logic                  link_xp_1_0_to_xp_2_0_pubflitv;
  logic                  link_xp_1_0_to_xp_2_0_lcrdv;
  logic [7:0]            link_xp_1_0_to_xp_2_0_rinfo;
  logic [15:0]           link_xp_1_0_to_xp_2_0_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_2_0_to_xp_1_0_flit;
  logic                  link_xp_2_0_to_xp_1_0_reqflitv;
  logic                  link_xp_2_0_to_xp_1_0_rspflitv;
  logic                  link_xp_2_0_to_xp_1_0_datflitv;
  logic                  link_xp_2_0_to_xp_1_0_snpflitv;
  logic                  link_xp_2_0_to_xp_1_0_pubflitv;
  logic                  link_xp_2_0_to_xp_1_0_lcrdv;
  logic [7:0]            link_xp_2_0_to_xp_1_0_rinfo;
  logic [15:0]           link_xp_2_0_to_xp_1_0_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_0_to_xp_1_1_flit;
  logic                  link_xp_1_0_to_xp_1_1_reqflitv;
  logic                  link_xp_1_0_to_xp_1_1_rspflitv;
  logic                  link_xp_1_0_to_xp_1_1_datflitv;
  logic                  link_xp_1_0_to_xp_1_1_snpflitv;
  logic                  link_xp_1_0_to_xp_1_1_pubflitv;
  logic                  link_xp_1_0_to_xp_1_1_lcrdv;
  logic [7:0]            link_xp_1_0_to_xp_1_1_rinfo;
  logic [15:0]           link_xp_1_0_to_xp_1_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_1_to_xp_1_0_flit;
  logic                  link_xp_1_1_to_xp_1_0_reqflitv;
  logic                  link_xp_1_1_to_xp_1_0_rspflitv;
  logic                  link_xp_1_1_to_xp_1_0_datflitv;
  logic                  link_xp_1_1_to_xp_1_0_snpflitv;
  logic                  link_xp_1_1_to_xp_1_0_pubflitv;
  logic                  link_xp_1_1_to_xp_1_0_lcrdv;
  logic [7:0]            link_xp_1_1_to_xp_1_0_rinfo;
  logic [15:0]           link_xp_1_1_to_xp_1_0_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_2_0_to_xp_2_1_flit;
  logic                  link_xp_2_0_to_xp_2_1_reqflitv;
  logic                  link_xp_2_0_to_xp_2_1_rspflitv;
  logic                  link_xp_2_0_to_xp_2_1_datflitv;
  logic                  link_xp_2_0_to_xp_2_1_snpflitv;
  logic                  link_xp_2_0_to_xp_2_1_pubflitv;
  logic                  link_xp_2_0_to_xp_2_1_lcrdv;
  logic [7:0]            link_xp_2_0_to_xp_2_1_rinfo;
  logic [15:0]           link_xp_2_0_to_xp_2_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_2_1_to_xp_2_0_flit;
  logic                  link_xp_2_1_to_xp_2_0_reqflitv;
  logic                  link_xp_2_1_to_xp_2_0_rspflitv;
  logic                  link_xp_2_1_to_xp_2_0_datflitv;
  logic                  link_xp_2_1_to_xp_2_0_snpflitv;
  logic                  link_xp_2_1_to_xp_2_0_pubflitv;
  logic                  link_xp_2_1_to_xp_2_0_lcrdv;
  logic [7:0]            link_xp_2_1_to_xp_2_0_rinfo;
  logic [15:0]           link_xp_2_1_to_xp_2_0_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_0_1_to_xp_1_1_flit;
  logic                  link_xp_0_1_to_xp_1_1_reqflitv;
  logic                  link_xp_0_1_to_xp_1_1_rspflitv;
  logic                  link_xp_0_1_to_xp_1_1_datflitv;
  logic                  link_xp_0_1_to_xp_1_1_snpflitv;
  logic                  link_xp_0_1_to_xp_1_1_pubflitv;
  logic                  link_xp_0_1_to_xp_1_1_lcrdv;
  logic [7:0]            link_xp_0_1_to_xp_1_1_rinfo;
  logic [15:0]           link_xp_0_1_to_xp_1_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_1_to_xp_0_1_flit;
  logic                  link_xp_1_1_to_xp_0_1_reqflitv;
  logic                  link_xp_1_1_to_xp_0_1_rspflitv;
  logic                  link_xp_1_1_to_xp_0_1_datflitv;
  logic                  link_xp_1_1_to_xp_0_1_snpflitv;
  logic                  link_xp_1_1_to_xp_0_1_pubflitv;
  logic                  link_xp_1_1_to_xp_0_1_lcrdv;
  logic [7:0]            link_xp_1_1_to_xp_0_1_rinfo;
  logic [15:0]           link_xp_1_1_to_xp_0_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_0_1_to_xp_0_2_flit;
  logic                  link_xp_0_1_to_xp_0_2_reqflitv;
  logic                  link_xp_0_1_to_xp_0_2_rspflitv;
  logic                  link_xp_0_1_to_xp_0_2_datflitv;
  logic                  link_xp_0_1_to_xp_0_2_snpflitv;
  logic                  link_xp_0_1_to_xp_0_2_pubflitv;
  logic                  link_xp_0_1_to_xp_0_2_lcrdv;
  logic [7:0]            link_xp_0_1_to_xp_0_2_rinfo;
  logic [15:0]           link_xp_0_1_to_xp_0_2_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_0_2_to_xp_0_1_flit;
  logic                  link_xp_0_2_to_xp_0_1_reqflitv;
  logic                  link_xp_0_2_to_xp_0_1_rspflitv;
  logic                  link_xp_0_2_to_xp_0_1_datflitv;
  logic                  link_xp_0_2_to_xp_0_1_snpflitv;
  logic                  link_xp_0_2_to_xp_0_1_pubflitv;
  logic                  link_xp_0_2_to_xp_0_1_lcrdv;
  logic [7:0]            link_xp_0_2_to_xp_0_1_rinfo;
  logic [15:0]           link_xp_0_2_to_xp_0_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_1_to_xp_2_1_flit;
  logic                  link_xp_1_1_to_xp_2_1_reqflitv;
  logic                  link_xp_1_1_to_xp_2_1_rspflitv;
  logic                  link_xp_1_1_to_xp_2_1_datflitv;
  logic                  link_xp_1_1_to_xp_2_1_snpflitv;
  logic                  link_xp_1_1_to_xp_2_1_pubflitv;
  logic                  link_xp_1_1_to_xp_2_1_lcrdv;
  logic [7:0]            link_xp_1_1_to_xp_2_1_rinfo;
  logic [15:0]           link_xp_1_1_to_xp_2_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_2_1_to_xp_1_1_flit;
  logic                  link_xp_2_1_to_xp_1_1_reqflitv;
  logic                  link_xp_2_1_to_xp_1_1_rspflitv;
  logic                  link_xp_2_1_to_xp_1_1_datflitv;
  logic                  link_xp_2_1_to_xp_1_1_snpflitv;
  logic                  link_xp_2_1_to_xp_1_1_pubflitv;
  logic                  link_xp_2_1_to_xp_1_1_lcrdv;
  logic [7:0]            link_xp_2_1_to_xp_1_1_rinfo;
  logic [15:0]           link_xp_2_1_to_xp_1_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_1_to_xp_1_2_flit;
  logic                  link_xp_1_1_to_xp_1_2_reqflitv;
  logic                  link_xp_1_1_to_xp_1_2_rspflitv;
  logic                  link_xp_1_1_to_xp_1_2_datflitv;
  logic                  link_xp_1_1_to_xp_1_2_snpflitv;
  logic                  link_xp_1_1_to_xp_1_2_pubflitv;
  logic                  link_xp_1_1_to_xp_1_2_lcrdv;
  logic [7:0]            link_xp_1_1_to_xp_1_2_rinfo;
  logic [15:0]           link_xp_1_1_to_xp_1_2_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_2_to_xp_1_1_flit;
  logic                  link_xp_1_2_to_xp_1_1_reqflitv;
  logic                  link_xp_1_2_to_xp_1_1_rspflitv;
  logic                  link_xp_1_2_to_xp_1_1_datflitv;
  logic                  link_xp_1_2_to_xp_1_1_snpflitv;
  logic                  link_xp_1_2_to_xp_1_1_pubflitv;
  logic                  link_xp_1_2_to_xp_1_1_lcrdv;
  logic [7:0]            link_xp_1_2_to_xp_1_1_rinfo;
  logic [15:0]           link_xp_1_2_to_xp_1_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_2_1_to_xp_2_2_flit;
  logic                  link_xp_2_1_to_xp_2_2_reqflitv;
  logic                  link_xp_2_1_to_xp_2_2_rspflitv;
  logic                  link_xp_2_1_to_xp_2_2_datflitv;
  logic                  link_xp_2_1_to_xp_2_2_snpflitv;
  logic                  link_xp_2_1_to_xp_2_2_pubflitv;
  logic                  link_xp_2_1_to_xp_2_2_lcrdv;
  logic [7:0]            link_xp_2_1_to_xp_2_2_rinfo;
  logic [15:0]           link_xp_2_1_to_xp_2_2_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_2_2_to_xp_2_1_flit;
  logic                  link_xp_2_2_to_xp_2_1_reqflitv;
  logic                  link_xp_2_2_to_xp_2_1_rspflitv;
  logic                  link_xp_2_2_to_xp_2_1_datflitv;
  logic                  link_xp_2_2_to_xp_2_1_snpflitv;
  logic                  link_xp_2_2_to_xp_2_1_pubflitv;
  logic                  link_xp_2_2_to_xp_2_1_lcrdv;
  logic [7:0]            link_xp_2_2_to_xp_2_1_rinfo;
  logic [15:0]           link_xp_2_2_to_xp_2_1_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_0_2_to_xp_1_2_flit;
  logic                  link_xp_0_2_to_xp_1_2_reqflitv;
  logic                  link_xp_0_2_to_xp_1_2_rspflitv;
  logic                  link_xp_0_2_to_xp_1_2_datflitv;
  logic                  link_xp_0_2_to_xp_1_2_snpflitv;
  logic                  link_xp_0_2_to_xp_1_2_pubflitv;
  logic                  link_xp_0_2_to_xp_1_2_lcrdv;
  logic [7:0]            link_xp_0_2_to_xp_1_2_rinfo;
  logic [15:0]           link_xp_0_2_to_xp_1_2_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_2_to_xp_0_2_flit;
  logic                  link_xp_1_2_to_xp_0_2_reqflitv;
  logic                  link_xp_1_2_to_xp_0_2_rspflitv;
  logic                  link_xp_1_2_to_xp_0_2_datflitv;
  logic                  link_xp_1_2_to_xp_0_2_snpflitv;
  logic                  link_xp_1_2_to_xp_0_2_pubflitv;
  logic                  link_xp_1_2_to_xp_0_2_lcrdv;
  logic [7:0]            link_xp_1_2_to_xp_0_2_rinfo;
  logic [15:0]           link_xp_1_2_to_xp_0_2_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_1_2_to_xp_2_2_flit;
  logic                  link_xp_1_2_to_xp_2_2_reqflitv;
  logic                  link_xp_1_2_to_xp_2_2_rspflitv;
  logic                  link_xp_1_2_to_xp_2_2_datflitv;
  logic                  link_xp_1_2_to_xp_2_2_snpflitv;
  logic                  link_xp_1_2_to_xp_2_2_pubflitv;
  logic                  link_xp_1_2_to_xp_2_2_lcrdv;
  logic [7:0]            link_xp_1_2_to_xp_2_2_rinfo;
  logic [15:0]           link_xp_1_2_to_xp_2_2_globalsig;

  logic [FLIT_WIDTH-1:0] link_xp_2_2_to_xp_1_2_flit;
  logic                  link_xp_2_2_to_xp_1_2_reqflitv;
  logic                  link_xp_2_2_to_xp_1_2_rspflitv;
  logic                  link_xp_2_2_to_xp_1_2_datflitv;
  logic                  link_xp_2_2_to_xp_1_2_snpflitv;
  logic                  link_xp_2_2_to_xp_1_2_pubflitv;
  logic                  link_xp_2_2_to_xp_1_2_lcrdv;
  logic [7:0]            link_xp_2_2_to_xp_1_2_rinfo;
  logic [15:0]           link_xp_2_2_to_xp_1_2_globalsig;


  //# Device Attachment Bundle Declarations
  //# =====================================
  // NI-to-router bundles model protocol adapters, request queues, and return
  // paths in the same location a production wrapper would stitch CHI/AXI ports.

  logic [FLIT_WIDTH-1:0] ni_ep_0_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_0_flit;
  logic                  ni_ep_0_tx_credit_valid;
  logic                  ni_ep_0_rx_credit_valid;
  logic [3:0]            ni_ep_0_qos_class;

  logic [FLIT_WIDTH-1:0] ni_ep_1_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_1_flit;
  logic                  ni_ep_1_tx_credit_valid;
  logic                  ni_ep_1_rx_credit_valid;
  logic [3:0]            ni_ep_1_qos_class;

  logic [FLIT_WIDTH-1:0] ni_ep_2_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_2_flit;
  logic                  ni_ep_2_tx_credit_valid;
  logic                  ni_ep_2_rx_credit_valid;
  logic [3:0]            ni_ep_2_qos_class;

  logic [FLIT_WIDTH-1:0] ni_ep_3_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_3_flit;
  logic                  ni_ep_3_tx_credit_valid;
  logic                  ni_ep_3_rx_credit_valid;
  logic [3:0]            ni_ep_3_qos_class;

  logic [FLIT_WIDTH-1:0] ni_ep_4_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_4_flit;
  logic                  ni_ep_4_tx_credit_valid;
  logic                  ni_ep_4_rx_credit_valid;
  logic [3:0]            ni_ep_4_qos_class;

  logic [FLIT_WIDTH-1:0] ni_ep_5_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_5_flit;
  logic                  ni_ep_5_tx_credit_valid;
  logic                  ni_ep_5_rx_credit_valid;
  logic [3:0]            ni_ep_5_qos_class;

  logic [FLIT_WIDTH-1:0] ni_ep_6_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_6_flit;
  logic                  ni_ep_6_tx_credit_valid;
  logic                  ni_ep_6_rx_credit_valid;
  logic [3:0]            ni_ep_6_qos_class;

  logic [FLIT_WIDTH-1:0] ni_ep_7_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_7_flit;
  logic                  ni_ep_7_tx_credit_valid;
  logic                  ni_ep_7_rx_credit_valid;
  logic [3:0]            ni_ep_7_qos_class;

  logic [FLIT_WIDTH-1:0] ni_ep_8_to_router_flit;
  logic [FLIT_WIDTH-1:0] router_to_ni_ep_8_flit;
  logic                  ni_ep_8_tx_credit_valid;
  logic                  ni_ep_8_rx_credit_valid;
  logic [3:0]            ni_ep_8_qos_class;


  //# Router Instance Stitching
  //# =========================

  xp_router_xp_0_0 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_0_0 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_out_xp_1_0(link_xp_0_0_to_xp_1_0_flit),
    .flit_in_xp_1_0(link_xp_1_0_to_xp_0_0_flit),
    .flit_out_xp_0_1(link_xp_0_0_to_xp_0_1_flit),
    .flit_in_xp_0_1(link_xp_0_1_to_xp_0_0_flit),
    .ep_0_flit_in(ni_ep_0_to_router_flit),
    .ep_0_flit_out(router_to_ni_ep_0_flit)
  );


  xp_router_xp_1_0 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_1_0 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_0_0(link_xp_0_0_to_xp_1_0_flit),
    .flit_out_xp_0_0(link_xp_1_0_to_xp_0_0_flit),
    .flit_out_xp_2_0(link_xp_1_0_to_xp_2_0_flit),
    .flit_in_xp_2_0(link_xp_2_0_to_xp_1_0_flit),
    .flit_out_xp_1_1(link_xp_1_0_to_xp_1_1_flit),
    .flit_in_xp_1_1(link_xp_1_1_to_xp_1_0_flit),
    .ep_1_flit_in(ni_ep_1_to_router_flit),
    .ep_1_flit_out(router_to_ni_ep_1_flit)
  );


  xp_router_xp_2_0 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_2_0 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_1_0(link_xp_1_0_to_xp_2_0_flit),
    .flit_out_xp_1_0(link_xp_2_0_to_xp_1_0_flit),
    .flit_out_xp_2_1(link_xp_2_0_to_xp_2_1_flit),
    .flit_in_xp_2_1(link_xp_2_1_to_xp_2_0_flit),
    .ep_2_flit_in(ni_ep_2_to_router_flit),
    .ep_2_flit_out(router_to_ni_ep_2_flit)
  );


  xp_router_xp_0_1 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_0_1 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_0_0(link_xp_0_0_to_xp_0_1_flit),
    .flit_out_xp_0_0(link_xp_0_1_to_xp_0_0_flit),
    .flit_out_xp_1_1(link_xp_0_1_to_xp_1_1_flit),
    .flit_in_xp_1_1(link_xp_1_1_to_xp_0_1_flit),
    .flit_out_xp_0_2(link_xp_0_1_to_xp_0_2_flit),
    .flit_in_xp_0_2(link_xp_0_2_to_xp_0_1_flit),
    .ep_3_flit_in(ni_ep_3_to_router_flit),
    .ep_3_flit_out(router_to_ni_ep_3_flit)
  );


  xp_router_xp_1_1 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_1_1 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_1_0(link_xp_1_0_to_xp_1_1_flit),
    .flit_out_xp_1_0(link_xp_1_1_to_xp_1_0_flit),
    .flit_in_xp_0_1(link_xp_0_1_to_xp_1_1_flit),
    .flit_out_xp_0_1(link_xp_1_1_to_xp_0_1_flit),
    .flit_out_xp_2_1(link_xp_1_1_to_xp_2_1_flit),
    .flit_in_xp_2_1(link_xp_2_1_to_xp_1_1_flit),
    .flit_out_xp_1_2(link_xp_1_1_to_xp_1_2_flit),
    .flit_in_xp_1_2(link_xp_1_2_to_xp_1_1_flit),
    .ep_4_flit_in(ni_ep_4_to_router_flit),
    .ep_4_flit_out(router_to_ni_ep_4_flit)
  );


  xp_router_xp_2_1 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_2_1 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_2_0(link_xp_2_0_to_xp_2_1_flit),
    .flit_out_xp_2_0(link_xp_2_1_to_xp_2_0_flit),
    .flit_in_xp_1_1(link_xp_1_1_to_xp_2_1_flit),
    .flit_out_xp_1_1(link_xp_2_1_to_xp_1_1_flit),
    .flit_out_xp_2_2(link_xp_2_1_to_xp_2_2_flit),
    .flit_in_xp_2_2(link_xp_2_2_to_xp_2_1_flit),
    .ep_5_flit_in(ni_ep_5_to_router_flit),
    .ep_5_flit_out(router_to_ni_ep_5_flit)
  );


  xp_router_xp_0_2 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_0_2 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_0_1(link_xp_0_1_to_xp_0_2_flit),
    .flit_out_xp_0_1(link_xp_0_2_to_xp_0_1_flit),
    .flit_out_xp_1_2(link_xp_0_2_to_xp_1_2_flit),
    .flit_in_xp_1_2(link_xp_1_2_to_xp_0_2_flit),
    .ep_6_flit_in(ni_ep_6_to_router_flit),
    .ep_6_flit_out(router_to_ni_ep_6_flit)
  );


  xp_router_xp_1_2 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_1_2 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_1_1(link_xp_1_1_to_xp_1_2_flit),
    .flit_out_xp_1_1(link_xp_1_2_to_xp_1_1_flit),
    .flit_in_xp_0_2(link_xp_0_2_to_xp_1_2_flit),
    .flit_out_xp_0_2(link_xp_1_2_to_xp_0_2_flit),
    .flit_out_xp_2_2(link_xp_1_2_to_xp_2_2_flit),
    .flit_in_xp_2_2(link_xp_2_2_to_xp_1_2_flit),
    .ep_7_flit_in(ni_ep_7_to_router_flit),
    .ep_7_flit_out(router_to_ni_ep_7_flit)
  );


  xp_router_xp_2_2 #(
    .DATA_WIDTH(DATA_WIDTH),
    .FLIT_WIDTH(FLIT_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_xp_2_2 (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_xp_2_1(link_xp_2_1_to_xp_2_2_flit),
    .flit_out_xp_2_1(link_xp_2_2_to_xp_2_1_flit),
    .flit_in_xp_1_2(link_xp_1_2_to_xp_2_2_flit),
    .flit_out_xp_1_2(link_xp_2_2_to_xp_1_2_flit),
    .ep_8_flit_in(ni_ep_8_to_router_flit),
    .ep_8_flit_out(router_to_ni_ep_8_flit)
  );


  //# Network Interface Instance Stitching
  //# ====================================

  ni_xp_xp_0_0 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_0_0 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_0_flit_in(ep_0_flit_in),
    .ep_0_flit_out(ep_0_flit_out),
    .ep_0_router_flit_in(ni_ep_0_to_router_flit),
    .ep_0_router_flit_out(router_to_ni_ep_0_flit)
  );


  ni_xp_xp_1_0 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_1_0 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_1_flit_in(ep_1_flit_in),
    .ep_1_flit_out(ep_1_flit_out),
    .ep_1_router_flit_in(ni_ep_1_to_router_flit),
    .ep_1_router_flit_out(router_to_ni_ep_1_flit)
  );


  ni_xp_xp_2_0 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_2_0 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_2_flit_in(ep_2_flit_in),
    .ep_2_flit_out(ep_2_flit_out),
    .ep_2_router_flit_in(ni_ep_2_to_router_flit),
    .ep_2_router_flit_out(router_to_ni_ep_2_flit)
  );


  ni_xp_xp_0_1 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_0_1 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_3_flit_in(ep_3_flit_in),
    .ep_3_flit_out(ep_3_flit_out),
    .ep_3_router_flit_in(ni_ep_3_to_router_flit),
    .ep_3_router_flit_out(router_to_ni_ep_3_flit)
  );


  ni_xp_xp_1_1 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_1_1 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_4_flit_in(ep_4_flit_in),
    .ep_4_flit_out(ep_4_flit_out),
    .ep_4_router_flit_in(ni_ep_4_to_router_flit),
    .ep_4_router_flit_out(router_to_ni_ep_4_flit)
  );


  ni_xp_xp_2_1 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_2_1 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_5_flit_in(ep_5_flit_in),
    .ep_5_flit_out(ep_5_flit_out),
    .ep_5_router_flit_in(ni_ep_5_to_router_flit),
    .ep_5_router_flit_out(router_to_ni_ep_5_flit)
  );


  ni_xp_xp_0_2 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_0_2 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_6_flit_in(ep_6_flit_in),
    .ep_6_flit_out(ep_6_flit_out),
    .ep_6_router_flit_in(ni_ep_6_to_router_flit),
    .ep_6_router_flit_out(router_to_ni_ep_6_flit)
  );


  ni_xp_xp_1_2 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_1_2 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_7_flit_in(ep_7_flit_in),
    .ep_7_flit_out(ep_7_flit_out),
    .ep_7_router_flit_in(ni_ep_7_to_router_flit),
    .ep_7_router_flit_out(router_to_ni_ep_7_flit)
  );


  ni_xp_xp_2_2 #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .NUM_ENDPOINTS(1)
  ) u_ni_xp_2_2 (
    .clk(clk),
    .rst_n(rst_n),
    .ep_8_flit_in(ep_8_flit_in),
    .ep_8_flit_out(ep_8_flit_out),
    .ep_8_router_flit_in(ni_ep_8_to_router_flit),
    .ep_8_router_flit_out(router_to_ni_ep_8_flit)
  );


endmodule
