
//----------------------------------------------------------------------------
// Auto-generated by finepaper | NoC: mesh_3x3 v1.0
//----------------------------------------------------------------------------
//#========================================================================
//#
//#  NI: Network Interface Bridge
//#
//#========================================================================
//#
//# Endpoint Bridge Configuration
//# =============================
//  - source_xp          : xp_0_0
//  - module_name        : ni_xp_xp_0_0
//  - variant_signature  : per-xp
//  - local_endpoints    : ep_0
//  - flit_width         : 128
//  - endpoint_count     : 1
//#

//  - ep_0     maps=ep_0             role=master protocol=axi4     data_width=64 buffer_depth=16 qos=disabled

//#
//# Feature Mask
//# ============

//  - protocol_decode  : generated

//  - request_queue    : generated

//  - response_queue   : generated

//  - credit_flow      : generated

//  - qos              : generated

//  - error_check      : generated

//  - trace            : masked

//#
//# Protocol Adapter Placeholders
//# =============================
//  - ingress_adapter : protocol-side request/data accepted into flit shell
//  - egress_adapter  : router return flits presented to endpoint protocol
//  - ordering_model  : preserves existing single-flit demo behavior
//#
//# Credit and Flow Control
//# =======================
//  - tx_credit_count : placeholder local transmit credit counter
//  - can_issue       : placeholder request admission decision
//  - response_queue  : placeholder router-to-endpoint return buffering
//----------------------------------------------------------------------------

module ni_xp_xp_0_0 #(
  parameter FLIT_WIDTH = 128,
  parameter NUM_ENDPOINTS = 1
) (
  input  logic clk,
  input  logic rst_n,
  // Endpoint-side interfaces (protocol side)

  input  logic [FLIT_WIDTH-1:0] ep_0_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_0_flit_out,
  // Router-side interfaces (flit side)

  output logic [FLIT_WIDTH-1:0] ep_0_router_flit_in,
  input  logic [FLIT_WIDTH-1:0] ep_0_router_flit_out
);


  //# ep_0 protocol conversion shell
  //# ===============================
  // Static framework stubs make this generated NI look like a protocol bridge
  // without claiming to implement AXI/CHI semantics yet.

  logic [3:0]            ep_0_opcode;
  logic                  ep_0_is_read;
  logic                  ep_0_is_write;
  fp_ni_protocol_decode #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .DATA_WIDTH(64)
  ) u_ep_0_protocol_decode (
    .flit_i(ep_0_flit_in),
    .opcode_o(ep_0_opcode),
    .is_read_o(ep_0_is_read),
    .is_write_o(ep_0_is_write)
  );


  logic [FLIT_WIDTH-1:0] ep_0_req_payload;
  logic                  ep_0_req_valid;
  logic                  ep_0_req_ready;
  fp_ni_request_queue #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .DEPTH(16)
  ) u_ep_0_request_queue (
    .clk(clk),
    .rst_n(rst_n),
    .payload_i(ep_0_flit_in),
    .valid_i(1'b1),
    .ready_o(ep_0_req_ready),
    .payload_o(ep_0_req_payload),
    .valid_o(ep_0_req_valid),
    .ready_i(1'b1)
  );


  logic [FLIT_WIDTH-1:0] ep_0_rsp_payload;
  logic                  ep_0_rsp_valid;
  logic                  ep_0_rsp_ready;
  fp_ni_response_queue #(
    .FLIT_WIDTH(FLIT_WIDTH),
    .DEPTH(16)
  ) u_ep_0_response_queue (
    .clk(clk),
    .rst_n(rst_n),
    .payload_i(ep_0_router_flit_out),
    .valid_i(1'b1),
    .ready_o(ep_0_rsp_ready),
    .payload_o(ep_0_rsp_payload),
    .valid_o(ep_0_rsp_valid),
    .ready_i(1'b1)
  );


  logic [7:0]            ep_0_tx_credit_count;
  logic                  ep_0_can_issue;
  fp_ni_credit_flow u_ep_0_credit_flow (
    .clk(clk),
    .rst_n(rst_n),
    .issue_i(1'b1),
    .return_credit_i(1'b1),
    .credit_count_o(ep_0_tx_credit_count),
    .can_issue_o(ep_0_can_issue)
  );


  logic [3:0]            ep_0_qos_class;
  fp_ni_qos_classifier #(
    .QOS_ENABLED(0)
  ) u_ep_0_qos_classifier (
    .opcode_i(ep_0_opcode),
    .qos_class_o(ep_0_qos_class)
  );


  logic                  ep_0_protocol_error;
  fp_ni_error_check #(
    .FLIT_WIDTH(FLIT_WIDTH)
  ) u_ep_0_error_check (
    .flit_i(ep_0_flit_in),
    .error_o(ep_0_protocol_error)
  );


  assign ep_0_router_flit_in = ep_0_flit_in;

  assign ep_0_flit_out = ep_0_router_flit_out;



endmodule
