
//----------------------------------------------------------------------------
// Auto-generated by finepaper | NoC: mesh_3x3 v1.0
//----------------------------------------------------------------------------
//#========================================================================
//#
//#  NI: Network Interface Bridge
//#
//#========================================================================
//#
//# Endpoint Bridge Configuration
//# =============================
//  - source_xp       : xp_0_1
//  - local_endpoints : ep_3
//  - flit_width      : 128
//  - endpoint_count  : 1
//#

//  - ep_3             role=slave  protocol=axi4     data_width=128 buffer_depth=16 qos=disabled

//#
//# Protocol Adapter Placeholders
//# =============================
//  - ingress_adapter : protocol-side request/data accepted into flit shell
//  - egress_adapter  : router return flits presented to endpoint protocol
//  - ordering_model  : preserves existing single-flit demo behavior
//#
//# Credit and Flow Control
//# =======================
//  - tx_credit_valid : placeholder for endpoint-to-router credit accounting
//  - rx_credit_valid : placeholder for router-to-endpoint return credits
//  - qos_class       : endpoint QoS metadata slot for future arbitration
//----------------------------------------------------------------------------

module ni_xp_xp_0_1 #(
  parameter FLIT_WIDTH = 128,
  parameter NUM_ENDPOINTS = 1
) (
  input  logic clk,
  input  logic rst_n,
  // Endpoint-side interfaces (protocol side)

  input  logic [FLIT_WIDTH-1:0] ep_3_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_3_flit_out,
  // Router-side interfaces (flit side)

  output logic [FLIT_WIDTH-1:0] ep_3_router_flit_in,
  input  logic [FLIT_WIDTH-1:0] ep_3_router_flit_out
);
  //# Endpoint passthrough datapath
  //# =============================
  // Generated protocol adapters are structural placeholders. Endpoint records
  // without explicit protocol ports keep the original direct flit passthrough.

  assign ep_3_router_flit_in = ep_3_flit_in;
  assign ep_3_flit_out = ep_3_router_flit_out;

endmodule
