// Auto-generated by finepaper | NoC: mesh_3x3 v1.0
// data_width=64 flit_width=128 addr_width=32

module xp_router_xp_1_2 #(
  parameter DATA_WIDTH = 64,
  parameter FLIT_WIDTH = 128,
  parameter ADDR_WIDTH = 32
) (
  input  logic clk,
  input  logic rst_n,
  // Endpoints: ep_7

  // Link to xp_1_1 (south)
  input  logic [FLIT_WIDTH-1:0] flit_in_xp_1_1,
  output logic [FLIT_WIDTH-1:0] flit_out_xp_1_1,
  // Link to xp_0_2 (east)
  input  logic [FLIT_WIDTH-1:0] flit_in_xp_0_2,
  output logic [FLIT_WIDTH-1:0] flit_out_xp_0_2,
  // Link to xp_2_2 (east)
  input  logic [FLIT_WIDTH-1:0] flit_in_xp_2_2,
  output logic [FLIT_WIDTH-1:0] flit_out_xp_2_2,
  input  logic [FLIT_WIDTH-1:0] ep_7_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_7_flit_out
);
  // XP at (1, 2) — routing logic placeholder
endmodule
