// Auto-generated by finepaper | NoC: mesh_3x3 v1.0
// data_width=64 flit_width=128 addr_width=32

module xp_router_xp_0_1 #(
  parameter DATA_WIDTH = 64,
  parameter FLIT_WIDTH = 128,
  parameter ADDR_WIDTH = 32
) (
  input  logic clk,
  input  logic rst_n,
  // Endpoints: 

  // Link to xp_0_0 (south)
  input  logic [FLIT_WIDTH-1:0] flit_in_xp_0_0,
  output logic [FLIT_WIDTH-1:0] flit_out_xp_0_0,
  // Link to xp_1_1 (east)
  input  logic [FLIT_WIDTH-1:0] flit_in_xp_1_1,
  output logic [FLIT_WIDTH-1:0] flit_out_xp_1_1,
  // Link to xp_0_2 (south)
  input  logic [FLIT_WIDTH-1:0] flit_in_xp_0_2,
  output logic [FLIT_WIDTH-1:0] flit_out_xp_0_2
);
  // XP at (0, 1) — routing logic placeholder
endmodule
