require 'fileutils'
require 'json'
require 'optparse'

module IpcraftGenerator
  class Error < StandardError; end

  class CLI
    def self.run(argv)
      options = {}

      OptionParser.new do |parser|
        parser.on('--manifest PATH', 'Ipcraft manifest JSON path') { |value| options[:manifest] = value }
        parser.on('--input PATH', 'Ipcraft project input JSON path') { |value| options[:input] = value }
        parser.on('--output DIR', 'Generated output directory') { |value| options[:output] = value }
      end.parse!(argv)
    rescue OptionParser::ParseError => error
      raise Error, error.message
    else
      raise Error, "unexpected argument: #{argv.first}" unless argv.empty?

      raise Error, '--manifest is required' unless options[:manifest]
      raise Error, '--input is required' unless options[:input]
      raise Error, '--output is required' unless options[:output]

      Generator.new(
        manifest: options.fetch(:manifest),
        input: options.fetch(:input),
        output: options.fetch(:output)
      ).generate

      puts "Generated ipcraft output in #{options.fetch(:output)}"
    end
  end

  class Generator
    def initialize(manifest:, input:, output:)
      @manifest_path = manifest
      @input_path = input
      @output_dir = output
    end

    def generate
      manifest = JSON.parse(File.read(@manifest_path))
      input = JSON.parse(File.read(@input_path))

      validate!(manifest, input)

      FileUtils.mkdir_p(@output_dir)
      if manifest.fetch('id') == 'finepaper.noc'
        generate_finepaper_noc(manifest, input)
      else
        generate_generic(manifest, input)
      end
    end

    private

    def validate!(manifest, input)
      raise Error, 'manifest schema must be ipcraft.manifest.v1' unless manifest['schema'] == 'ipcraft.manifest.v1'
      raise Error, 'input schema must be ipcraft.noc.project.v1' unless input['schema'] == 'ipcraft.noc.project.v1'
      raise Error, 'input package does not match manifest id' unless input['package'] == manifest['id']
    end

    def output_manifest(manifest, input)
      {
        ipcore: manifest.fetch('id'),
        schema: input.fetch('schema'),
        instance_count: input.fetch('instances', []).size,
        connection_count: input.fetch('connections', []).size
      }
    end

    def generate_generic(manifest, input)
      write_json(File.join(@output_dir, 'manifest.json'), output_manifest(manifest, input))
    end

    def generate_finepaper_noc(manifest, input)
      router_module = module_id_for_role(manifest, 'router', 'XP')
      endpoint_module = module_id_for_role(manifest, 'endpoint', 'Endpoint')
      routers = instances_for_module(input, router_module)
      endpoints = instances_for_module(input, endpoint_module)

      rtl_dir = File.join(@output_dir, 'rtl')
      FileUtils.mkdir_p(rtl_dir)
      File.write(File.join(rtl_dir, 'top.v'), finepaper_top(routers, endpoints))
      File.write(File.join(@output_dir, 'filelist.f'), "rtl/top.v\n")
      write_json(File.join(@output_dir, 'manifest.json'), finepaper_output_manifest(manifest, input, routers, endpoints))
    end

    def module_id_for_role(manifest, role, fallback)
      mappings = manifest.dig('generation', 'module_mappings') || {}
      mappings.find { |_module_id, mapped_role| mapped_role == role }&.first || fallback
    end

    def instances_for_module(input, module_id)
      input.fetch('instances', []).select { |instance| instance['module'] == module_id }
    end

    def finepaper_output_manifest(manifest, input, routers, endpoints)
      output_manifest(manifest, input).merge(
        routers: routers.size,
        endpoints: endpoints.size
      )
    end

    def finepaper_top(routers, endpoints)
      lines = [
        '// Generated by ipcraft_generator for finepaper.noc',
        'module top;',
        '  // Routers'
      ]
      lines.concat(routers.map { |router| "  // XP #{instance_summary(router)}" })
      lines << '  // Endpoints'
      lines.concat(endpoints.map { |endpoint| "  // Endpoint #{instance_summary(endpoint)}" })
      lines << 'endmodule'
      "#{lines.join("\n")}\n"
    end

    def instance_summary(instance)
      parameters = instance.fetch('parameters', {})
      parameter_text = parameters.map { |key, value| "#{key}=#{value}" }.join(', ')
      [instance.fetch('id'), parameter_text].reject(&:empty?).join(' ')
    end

    def write_json(path, value)
      File.write(path, "#{JSON.pretty_generate(value)}\n")
    end
  end
end
