
//----------------------------------------------------------------------------
// Auto-generated by finepaper | NoC: mesh_3x3 v1.0
//----------------------------------------------------------------------------
//#========================================================================
//#
//#  SMXP: Synthetic Mesh Cross Point
//#
//#========================================================================
//#
//# Module
//# ======
//  - module_name       : xp_router_xp_0_0
//  - source_xp         : xp_0_0
//  - node_id           : 0
//  - position          : (0, 0)
//  - variant_signature : per-xp
//  - local_ports       : 1
//#
//# Crosspoint Configuration
//# ========================
//  - DATA_WIDTH        : 64
//  - FLIT_WIDTH        : 128
//  - ADDR_WIDTH        : 32
//  - routing_algorithm : xy
//  - virtual_channels  : 2
//  - buffer_depth      : 8
//  - endpoint_slots    : ep_0
//#
//# Mesh Port Matrix
//# ================

//# Mesh Port: E

//  - slice0           : neighbor=xp_1_0 port_suffix=e virtual_networks=REQ,RSP,DAT,SNP,PUB credit_mode=local-return


//# Mesh Port: W

//  - state            : not present for this variant


//# Mesh Port: N

//  - state            : not present for this variant


//# Mesh Port: S

//  - slice0           : neighbor=xp_0_1 port_suffix=s virtual_networks=REQ,RSP,DAT,SNP,PUB credit_mode=local-return


//#
//# Protocol Channel Placeholders
//# =============================
//  - REQ : address/control request flits, ordered by routing class
//  - RSP : response flits with completion and retry status
//  - DAT : data flits with poison/check metadata carried beside payload
//  - SNP : snoop request/response placeholders for coherent fabrics
//  - PUB : public configuration and maintenance sideband channel
//#
//# Internal Signals - Automatic Declarations
//# =========================================
//  - route_select_table[local, E, W, N, S]
//  - ingress_credit_count[virtual_channel]
//  - egress_credit_count[virtual_channel]
//  - qos_arbiter_grant[REQ, RSP, DAT, SNP, PUB]
//  - vc_occupancy_snapshot[local_port][virtual_channel]
//----------------------------------------------------------------------------

module xp_router_xp_0_0 #(
  parameter DATA_WIDTH = 64,
  parameter FLIT_WIDTH = 128,
  parameter ADDR_WIDTH = 32
) (
  input  logic clk,
  input  logic rst_n,
  // Endpoints: ep_0

  // Link to xp_1_0 (east)
  input  logic [FLIT_WIDTH-1:0] flit_in_xp_1_0,
  output logic [FLIT_WIDTH-1:0] flit_out_xp_1_0,
  // Link to xp_0_1 (south)
  input  logic [FLIT_WIDTH-1:0] flit_in_xp_0_1,
  output logic [FLIT_WIDTH-1:0] flit_out_xp_0_1,
  input  logic [FLIT_WIDTH-1:0] ep_0_flit_in,
  output logic [FLIT_WIDTH-1:0] ep_0_flit_out
);

  //# Parameter Conversion Notes
  //# ==========================
  // This generated shell intentionally mirrors the shape of production NoC IP:
  // config values are surfaced here so reports show routing, buffering, and
  // credit policy next to the structural port map.
  //
  // u_route_decode:
  //   - consumes destination node id and selected virtual channel
  //   - applies XY routing preference
  //   - arbitrates between local egress and mesh directions
  //
  // u_credit_accounting:
  //   - tracks 2 virtual channels
  //   - assumes 8 flit entries per ingress queue
  //   - returns local credits on simplified flit acceptance
  //
  // u_channel_switch:
  //   - maps compact demo flits onto REQ/RSP/DAT/SNP/PUB placeholder channels
  //   - preserves the existing finepaper single-flit interface for tests
  logic [ADDR_WIDTH-1:0] route_dst_addr;
  logic [2:0]            route_select;
  logic [7:0]            credit_level;
  logic [FLIT_WIDTH-1:0] switched_flit;

  assign route_dst_addr = '0;

  fp_xp_route_decode #(
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_route_decode (
    .dst_addr_i(route_dst_addr),
    .route_sel_o(route_select)
  );

  fp_xp_credit_accounting #(
    .VC_COUNT(2),
    .BUFFER_DEPTH(8)
  ) u_credit_accounting (
    .clk(clk),
    .rst_n(rst_n),
    .flit_accept_i(1'b1),
    .credit_level_o(credit_level)
  );

  fp_xp_channel_switch #(
    .FLIT_WIDTH(FLIT_WIDTH)
  ) u_channel_switch (
    .flit_i(ep_0_flit_in),
    .flit_o(switched_flit)
  );
endmodule
